name: Discord Release Notification

on:
  release:
    types: [published]   # triggers when a release is published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Secret length: ${#DISCORD_WEBHOOK}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_IN }}
          
      - name: Send Discord notification (IN)
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_IN }}
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          title: "New Release Published"
          nodetail: true
          description: |
            **${{ github.event.release.name }}**
            ${{ github.event.release.body }}
            Click [here](http://builder.itad.services) to download

          url: ${{ github.event.release.html_url }}
          color: 0x00ff99
          username: GitHub Releases
      
