name: Discord Release Notification v3

on:
  push:
    tags:
      - 'v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webhook_name:
          - WEBHOOK_IN
          - WEBHOOK_CA

    steps:
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets[matrix.webhook_name] }}
          title: "New Release Published"
          nodetail: true
          description: |
            **${{ github.event.release.name }}**
            
            ${{ github.event.release.body }}

            Click [here](http://builder.itad.services) to download
            Click [here](${{ github.event.release.html_url }}) for the release


          url: ${{ http://builder.itad.services}}
          color: 0x00ff99
          username: GitHub Releases
      
